name: PHP CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP without composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.11'
        tools: none
    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.1

    - name: Run composer install
      run: composer install -n --prefer-dist

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
    - name: Create temporary sqlite database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run laravel database migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
    - name: Run lint
      run: make lint
    - name: Run test
      run: make test
    - name: Run test & publish code coverage
      uses: paambaati/codeclimate-action@v4.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #with:
        #coverageCommand: make test-coverage
        #coverageLocations: ${{ github.workplace }}/build/logs/clover.xml:clover
        #debug: true