name: PHP CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3

      - name: Db_show1
        run: php artisan db:show
        continue-on-error: true

      - name: Setup project
        run: make setup

      - name: Db_show2
        run: php artisan db:show
        continue-on-error: true

      - name: Run tests
        run: |
          vendor/bin/phpunit
          php artisan db:show --format=json
        continue-on-error: true

      - name: Check lint
        run: make lint

      - name: Db_show22
        run: php artisan db:show
        continue-on-error: true

      - name: Run tests & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true
      - name: Db_show3
        run: php artisan db:show
        continue-on-error: true